name: Auto Update M3U8 Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  # প্রতি ১০ মিনিট পরপর রান হবে
  workflow_dispatch:        # ম্যানুয়ালি রান করার অপশন

permissions:
  contents: write  # গিটহাবে ফাইল কমিট ও পুশ করার অনুমতি দেওয়ার জন্য

jobs:
  update-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers and Dependencies
        run: |
          playwright install --with-deps chromium

      - name: Run script to generate M3U playlist
        run: python main.py

      - name: Commit and push if playlist changed
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add playlist.m3u "Crichd page Link.json"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update playlist and json files [skip ci]" && git push)
